spring.config.import=optional:file:.env[.properties]

spring.mongodb.uri=${MONGODB_URI}

spring.data.mongodb.auto-index-creation=true

spring.security.user.name=${SPRING_SECURITY_DEV_USER:default_dev_user}
spring.security.user.password=${SPRING_SECURITY_DEV_PASSWORD:default_dev_password}

clerk.issuer=${CLERK_ISSUER}
clerk.jwks-url=${CLERK_JWKS_URL}
clerk.webhook.secret=${CLERK_WEBHOOK_SECRET}

server.servlet.context-path=/api/v1.0

# file upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

logging.level.org.springframework.security=TRACE